### PR TITLE
Upstream/master

### PR DESCRIPTION
**Pull request by Arr0way**
Added CentOS 7 Dradis Install Guide

### CODE REVIEW

**Comment by etdsoft** [comment]
can we merge this into the CE docs site please?

@Arr0way 👍 many thanks!

**Comment by Arr0way** [comment]
No problem, did you guys ever get around to merging this?

**Comment by etdsoft** [comment]
@Arr0way this is now merged and published here:

https://dradisframework.com/ce/documentation/install_centos.html

I had to clean up bits and pieces and reformat because this repo isn't 100% a match to what we're using today.

Also, I've added an attribution section at the bottom, if you'd like me to include other details (name, company, etc.) or change the link, please let me know.

**Comment by Arr0way** [comment]
@etdsoft Nice, thanks - any chance you could fix the top link :)

**Comment by etdsoft** [comment]
@Arr0way fixed!

**Pull request closed without merging**
